import { NextResponse } from "next/server";
import { getServerUser } from "@/lib/auth-server";
import { prisma } from "@/lib/prisma";
// ✅ Import the Enums directly from your generated client
import { Priority, TaskStatus } from "@prisma/client";

// 1. Define JSON shape
interface ImportTask {
  Day?: number;
  "Task Title"?: string;
  Description?: string;
  "Estimated Time (min)"?: number;
  Priority?: string;
  Subtasks?: string[];
}

// 2. Robust Priority Mapper (Maps "High"/"HIGH" -> Priority.high)
function mapPriority(p?: string): Priority {
  if (!p) return Priority.medium; // Default

  const normalized = p.toLowerCase().trim();

  // Explicitly map common AI outputs to your Schema values
  switch (normalized) {
    case "urgent": return Priority.urgent;
    case "high":   return Priority.high;
    case "low":    return Priority.low;
    case "medium": return Priority.medium;
    default:       return Priority.medium; // Fallback
  }
}

export async function POST(req: Request) {
  try {
    const user = await getServerUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const body = await req.json();
    const { planName, tasks, startDate, isAI } = body ?? {};

    if (!tasks || !Array.isArray(tasks)) {
      return NextResponse.json({ error: "Invalid tasks data" }, { status: 400 });
    }

    const startObj = new Date(startDate || new Date());

    const createdPlan = await prisma.plan.create({
      data: {
        userId: user.id,
        title: planName || "New Plan",
        description: isAI ? "Generated by AI Architect" : "Imported Plan",
        startDate: startObj,
        tasks: {
          create: tasks.map((t: ImportTask) => {
            // Calculate date based on Day offset
            const taskDate = new Date(startObj);
            const dayOffset = (t.Day || 1) - 1;
            taskDate.setDate(taskDate.getDate() + dayOffset);

            return {
              userId: user.id,
              title: t["Task Title"] || "Untitled Task",
              description: t.Description || "",
              estimatedMinutes: t["Estimated Time (min)"] || 30,
              
              // ✅ FIX: Maps to 'high', 'medium', etc. (lowercase)
              priority: mapPriority(t.Priority),
              
              date: taskDate,
              
              // ✅ FIX: Use strict lowercase Enum 'pending'
              status: TaskStatus.pending, 
              
              subtasks: {
                create: (t.Subtasks || []).map((subTitle: string) => ({
                  title: subTitle,
                  completed: false
                }))
              }
            };
          })
        }
      },
      include: {
        tasks: {
          include: { subtasks: true }
        }
      }
    });

    return NextResponse.json(createdPlan, { status: 201 });
  } catch (error) {
    console.error("Import JSON error:", error);
    const message = error instanceof Error ? error.message : "Import failed";
    return NextResponse.json({ error: message, details: String(error) }, { status: 500 });
  }
}