import { NextResponse } from "next/server";
import { getServerUser } from "@/lib/auth-server";
import { prisma } from "@/lib/prisma";
import { billing } from "@domain"; // ✅ Import billing service
import { Priority, TaskStatus } from "@prisma/client";

// 1. Define JSON shape
interface ImportTask {
  Day?: number;
  "Task Title"?: string;
  Description?: string;
  "Estimated Time (min)"?: number;
  Priority?: string;
  Subtasks?: string[];
  Resources?: string[]; // Added to match AI output
  Outcome?: string;     // Added to match AI output
}

// 2. Robust Priority Mapper
function mapPriority(p?: string): Priority {
  if (!p) return Priority.medium;
  const normalized = p.toLowerCase().trim();
  switch (normalized) {
    case "urgent": return Priority.urgent;
    case "high":   return Priority.high;
    case "low":    return Priority.low;
    default:       return Priority.medium;
  }
}

export async function POST(req: Request) {
  try {
    const user = await getServerUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const body = await req.json();
    const { planName, tasks, startDate, isAI } = body ?? {};

    if (!tasks || !Array.isArray(tasks)) {
      return NextResponse.json({ error: "Invalid tasks data" }, { status: 400 });
    }

    // 3. Date Normalization
    const baseDate = new Date(startDate || new Date());
    baseDate.setUTCHours(12, 0, 0, 0); 

    // 4. Create Plan Transaction
    const createdPlan = await prisma.plan.create({
      data: {
        userId: user.id,
        title: planName || "New Plan",
        description: isAI ? "Generated by AI Architect" : "Imported Plan",
        startDate: baseDate,
        // Approximate end date based on task count
        endDate: new Date(new Date(baseDate).setDate(baseDate.getDate() + tasks.length)),
        tasks: {
          create: tasks.map((t: ImportTask) => {
            const dayOffset = (t.Day || 1) - 1;
            const taskDate = new Date(baseDate);
            taskDate.setDate(taskDate.getDate() + dayOffset);

            // Construct rich description if new fields exist
            let richDescription = t.Description || "";
            if (t.Outcome) richDescription += `\n\n🎯 Outcome: ${t.Outcome}`;
            if (t.Resources && t.Resources.length > 0) richDescription += `\n\n📚 Resources:\n${t.Resources.join('\n')}`;

            return {
              userId: user.id,
              title: t["Task Title"] || "Untitled Task",
              description: richDescription,
              estimatedMinutes: Number(t["Estimated Time (min)"]) || 30,
              priority: mapPriority(t.Priority),
              status: TaskStatus.pending,
              date: taskDate,
              subtasks: {
                create: (t.Subtasks || []).map((subTitle: string) => ({
                  title: subTitle,
                  completed: false
                }))
              }
            };
          })
        }
      },
      select: { id: true } 
    });

    // ✅ 5. CHARGE CREDIT (Only if it was an AI plan)
    if (isAI) {
        try {
            await billing.incrementAIUsage(user.id);
        } catch (billingError) {
            console.error("Failed to deduct credit:", billingError);
            // Optionally: decide if you want to fail the request or just log it.
            // Usually, we log it but let the user have their plan if it was already created.
        }
    }

    return NextResponse.json(createdPlan, { status: 201 });
  } catch (error) {
    console.error("Import JSON error:", error);
    const message = error instanceof Error ? error.message : "Import failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}