import { NextResponse } from "next/server";
import { getServerUser } from "@/lib/auth-server";
import { prisma } from "@/lib/prisma";
import { billing } from "@gritorquit/domain"; 
// ✅ FIX: Import 'Prisma' to access InputJsonValue type
import { Priority, TaskStatus, Prisma } from "@prisma/client";

// --- 1. Helper to normalize Data Inputs ---
const getVal = (obj: unknown, keys: string[], defaultVal: unknown = undefined) => {
  const record = obj as Record<string, unknown>;
  if (!record) return defaultVal;
  
  for (const k of keys) {
    if (record[k] !== undefined && record[k] !== null) return record[k];
  }
  return defaultVal;
};

// --- 2. Robust Priority Mapper ---
function mapPriority(p?: string): Priority {
  if (!p) return Priority.medium;
  const normalized = p.toLowerCase().trim();
  switch (normalized) {
    case "urgent": return Priority.urgent;
    case "high":   return Priority.high;
    case "low":    return Priority.low;
    default:       return Priority.medium;
  }
}

export async function POST(req: Request) {
  try {
    const user = await getServerUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const body = await req.json();
    const { planName, tasks, startDate, isAI } = body ?? {};

    if (!tasks || !Array.isArray(tasks)) {
      return NextResponse.json({ error: "Invalid tasks data" }, { status: 400 });
    }

    // 3. Date Normalization
    const baseDate = new Date(startDate || new Date());
    baseDate.setUTCHours(12, 0, 0, 0); 

    // 4. Create Plan Transaction
    const createdPlan = await prisma.plan.create({
      data: {
        user: { connect: { id: user.id } },
        title: planName || "New Plan",
        description: isAI ? "Generated by AI Architect" : "Imported Plan",
        startDate: baseDate,
        endDate: new Date(new Date(baseDate).setDate(baseDate.getDate() + tasks.length)),
        tasks: {
          create: tasks.map((t: Record<string, unknown>) => {
            // A. Resolve Keys
            const dayVal = getVal(t, ["day", "Day"], 1);
            const titleVal = getVal(t, ["title", "Task Title"], "Untitled Task") as string;
            const descVal = getVal(t, ["description", "Description"], "") as string;
            const estMinVal = getVal(t, ["estimatedMinutes", "Estimated Time (min)"], 30);
            const priorityVal = getVal(t, ["priority", "Priority"], "Medium") as string;
            
            // B. Calculate Date
            const dayOffset = (Number(dayVal) || 1) - 1;
            const taskDate = new Date(baseDate);
            taskDate.setDate(taskDate.getDate() + dayOffset);

            // C. Handle Subtasks
            const rawSubtasks = getVal(t, ["subtasks", "Subtasks"], []) as unknown[];
            const subtasksCreate = rawSubtasks.map((st) => {
                const title = (typeof st === 'string' 
                    ? st 
                    : (st as Record<string, unknown>)?.title || "Step") as string;
                
                return {
                    title,
                    completed: false
                };
            });

            // D. Handle Metadata (Outcome & Resources)
            const rawResources = getVal(t, ["resources", "Resources"], []) as unknown[];
            const outcomeVal = getVal(t, ["outcome", "Outcome"], undefined) as string | undefined;
            
            const formattedResources = rawResources.map((res) => {
                if (typeof res === 'string') return { title: "Resource", url: res };
                // ✅ FIX: Cast to Prisma.InputJsonValue instead of 'any' to satisfy ESLint
                return res as Prisma.InputJsonValue; 
            });

            const metadataPayload = {
                outcome: outcomeVal || null,
                resources: formattedResources || [],
                generatedBy: isAI ? "AI_Architect" : "Import"
            };

            return {
              user: { connect: { id: user.id } }, 
              title: titleVal,
              description: descVal,
              estimatedMinutes: Number(estMinVal),
              priority: mapPriority(priorityVal),
              status: TaskStatus.pending,
              date: taskDate,
              
              subtasks: {
                create: subtasksCreate
              },

              // ✅ FIX: Cast to Prisma.InputJsonValue instead of 'any'
              metadata: metadataPayload as Prisma.InputJsonValue
            };
          })
        }
      },
      select: { id: true } 
    });

    // 5. Deduct Credit
    if (isAI) {
        try {
            await billing.incrementAIUsage(user.id);
        } catch (billingError) {
            console.warn("Failed to deduct credit, but plan was created:", billingError);
        }
    }

    return NextResponse.json(createdPlan, { status: 201 });
  } catch (error) {
    console.error("Import JSON error:", error);
    const message = error instanceof Error ? error.message : "Import failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}