import React, { useState, useEffect, useRef } from 'react';
import { View, Text, ScrollView, TouchableOpacity, TextInput, KeyboardAvoidingView, Platform, ActivityIndicator, Alert, AppState } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { database } from '../../db';
import Note from '../../db/models/Note';
import { Q } from '@nozbe/watermelondb';
import withObservables from '@nozbe/with-observables';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../../context/ThemeContext';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as Haptics from 'expo-haptics';
import { map } from 'rxjs/operators';
import { getStoredSession } from '../../lib/nativeAuth';
import { config } from '../../config';

interface NoteEditorProps {
  note: Note;
}

const NoteEditor: React.FC<NoteEditorProps> = ({ note }) => {
  const router = useRouter();
  const { colors } = useTheme();
  
  const [title, setTitle] = useState(note?.title || '');
  const [content, setContent] = useState(note?.content || '');
  const [isRefining, setIsRefining] = useState(false);

  const categories = ['GENERAL', 'YOUTUBE', 'COURSE', 'PROJECT', 'OTHER'];

  const handleSave = async (currentTitle: string, currentContent: string) => {
    if (!note) return;
    try {
      await database.write(async () => {
        await note.update(n => {
          n.title = currentTitle;
          n.content = currentContent;
          // Mark as pending to trigger sync
          if (n.syncStatus !== 'created') {
            n.syncStatus = 'updated';
          }
        });
      });
    } catch (e) {
      console.error("Auto-save failed", e);
    }
  };

  // Auto-save logic
  useEffect(() => {
    const timeoutId = setTimeout(() => {
      if (title !== note.title || content !== note.content) {
        handleSave(title, content);
      }
    }, 1000); // 1s debounce

    return () => clearTimeout(timeoutId);
  }, [title, content]);

  // AppState Listener for Background Saving
  useEffect(() => {
    const subscription = AppState.addEventListener('change', nextAppState => {
      if (nextAppState === 'background' || nextAppState === 'inactive') {
        if (title !== note.title || content !== note.content) {
          handleSave(title, content);
        }
      }
    });
    return () => subscription.remove();
  }, [title, content, note]);

  const handleExportPdf = async () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    try {
      const html = `
      <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica'; padding: 40px; color: #111827; }
          h1 { font-size: 28px; text-transform: uppercase; border-bottom: 4px solid #6366f1; padding-bottom: 15px; margin-bottom: 30px; font-weight: 900; font-style: italic; }
          .content { font-size: 16px; line-height: 1.6; white-space: pre-wrap; color: #374151; }
          .footer { font-size: 10px; color: #9ca3af; text-transform: uppercase; margin-top: 60px; border-top: 1px solid #e5e7eb; padding-top: 20px; font-weight: bold; font-style: italic; letter-spacing: 1px; }
        </style>
      </head>
      <body>
        <h1>${title || 'Untitled Note'}</h1>
        <div class="content">${content}</div>
        <div class="footer">Archive Record Generated by grit.io // ${new Date().toLocaleDateString()} // Confidential</div>
      </body>
      </html>
      `;
      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (e) {
      Alert.alert("Error", "Failed to generate PDF signal");
    }
  };

  const updateCategory = async (cat: string) => {
    Haptics.selectionAsync();
    await database.write(async () => {
      await note.update(n => {
        n.category = cat;
        if (n.syncStatus !== 'created') n.syncStatus = 'updated';
      });
    });
  };

  const handleDelete = async () => {
    Alert.alert(
      "Confirm Deletion",
      "Are you sure you want to permanently delete this neural record?",
      [
        { text: "Cancel", style: "cancel" },
        { 
          text: "Delete", 
          style: "destructive",
          onPress: async () => {
            await database.write(async () => {
              await note.markAsDeleted();
            });
            router.back();
            Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
          }
        }
      ]
    );
  };

  const handleAIRefine = async () => {
    if (!content.trim()) {
      Alert.alert("Buffer Empty", "You need to add some content before AI can refine it.");
      return;
    }
    
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    setIsRefining(true);
    
    try {
      const session = await getStoredSession();
      if (!session) throw new Error("Authentication required");

      const res = await fetch(`${config.apiUrl}/api/ai/refine-note`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${session.access_token}`
        },
        body: JSON.stringify({ content }),
      });

      if (!res.ok) throw new Error("Neural synthesis failed");

      const data = await res.json();
      setContent(data.refinedContent);
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch (e: any) {
      Alert.alert("Refinement Error", e.message);
    } finally {
      setIsRefining(false);
    }
  };

  return (
    <KeyboardAvoidingView 
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'} 
      style={{ flex: 1, backgroundColor: colors.primary }}
    >
      {/* Top Bar Protocol */}
      <View className="p-6 pt-16 border-b border-[var(--border-color)] bg-[var(--bg-card)] shadow-sm">
        <View className="flex-row items-center justify-between mb-8">
          <TouchableOpacity onPress={() => router.back()} className="w-12 h-12 items-center justify-center bg-[var(--bg-secondary)] rounded-2xl border border-[var(--border-color)]">
            <Ionicons name="chevron-back" size={24} color={colors.textSecondary} />
          </TouchableOpacity>
          
          <View className="flex-row gap-3">
            <TouchableOpacity 
              onPress={handleAIRefine}
              disabled={isRefining}
              className={`flex-row items-center gap-2 px-4 py-3 rounded-2xl border ${
                isRefining ? 'bg-[var(--bg-secondary)] border-[var(--border-color)] opacity-50' : 'bg-indigo-500/10 border-indigo-500/20'
              }`}
            >
              {isRefining ? (
                <ActivityIndicator size="small" color="#6366f1" />
              ) : (
                <>
                  <Ionicons name="sparkles" size={14} color="#6366f1" />
                  <Text className="text-[10px] font-black uppercase tracking-widest text-indigo-500 italic">Refine</Text>
                </>
              )}
            </TouchableOpacity>
            <TouchableOpacity 
              onPress={handleExportPdf}
              className="w-12 h-12 rounded-2xl bg-[var(--bg-secondary)] items-center justify-center border border-[var(--border-color)]"
            >
              <Ionicons name="download-outline" size={20} color={colors.accent} />
            </TouchableOpacity>
            <TouchableOpacity 
              onPress={handleDelete}
              className="w-12 h-12 rounded-2xl bg-rose-500/10 items-center justify-center border border-rose-500/20"
            >
              <Ionicons name="trash-outline" size={20} color="#F43F5E" />
            </TouchableOpacity>
          </View>
        </View>

        <ScrollView horizontal showsHorizontalScrollIndicator={false} className="flex-row">
          {categories.map(cat => (
            <TouchableOpacity
              key={cat}
              onPress={() => updateCategory(cat)}
              className={`mr-3 px-6 py-3 rounded-xl border transition-all ${
                note.category === cat 
                  ? 'bg-[var(--accent-color)] border-[var(--accent-color)] shadow-lg shadow-[var(--accent-color)]/20' 
                  : 'bg-[var(--bg-secondary)] border border-[var(--border-color)]'
              }`}
            >
              <Text className={`text-[10px] font-black uppercase tracking-widest ${
                note.category === cat ? 'text-[var(--bg-primary)]' : 'text-[var(--text-secondary)]'
              }`}>
                {cat}
              </Text>
            </TouchableOpacity>
          ))}
        </ScrollView>
      </View>

      <ScrollView className="flex-1 bg-[var(--bg-primary)]" contentContainerStyle={{ padding: 24, paddingBottom: 100 }} showsVerticalScrollIndicator={false}>
        <TextInput
          value={title}
          onChangeText={setTitle}
          placeholder="ENTER TITLE..."
          placeholderTextColor={`${colors.textSecondary}40`}
          className="text-4xl font-black text-[var(--text-primary)] italic uppercase tracking-tighter mb-8"
          multiline
        />
        
        <View className="bg-[var(--bg-card)] border border-[var(--border-color)] rounded-[3rem] p-8 shadow-sm min-h-[400px]">
          <TextInput
            value={content}
            onChangeText={setContent}
            placeholder="Begin synthesizing neural patterns..."
            placeholderTextColor={`${colors.textSecondary}40`}
            className="flex-1 w-full text-lg font-black italic text-[var(--text-primary)] uppercase tracking-tighter text-left"
            multiline
            textAlignVertical="top"
          />
        </View>
      </ScrollView>
    </KeyboardAvoidingView>
  );
};

const EnhancedNoteEditor = withObservables(['id'], ({ id }) => ({
  note: database.get<Note>('notes').query(Q.where('id', id)).observe().pipe(map(rows => rows[0] || null)),
}))(({ note }: { note: Note | null }) => {
  const { colors } = useTheme();
  const router = useRouter();

  if (!note) {
    return (
      <View className="flex-1 items-center justify-center bg-[var(--bg-primary)] p-10">
        <View className="w-24 h-24 bg-[var(--bg-secondary)] rounded-full items-center justify-center mb-10 border border-[var(--border-color)] shadow-inner">
          <Ionicons name="document-text-outline" size={48} color={colors.textSecondary} style={{ opacity: 0.2 }} />
        </View>
        <Text className="text-base font-black uppercase tracking-[0.2em] text-[var(--text-secondary)] text-center leading-relaxed">
          Neural record not found{'\n'}in local archive.
        </Text>
        <TouchableOpacity
          onPress={() => router.replace('/(drawer)/notes')}
          className="mt-12 bg-[var(--accent-color)] px-12 py-6 rounded-[2rem] shadow-xl shadow-[var(--accent-color)]/20"
        >
          <Text className="text-xs font-black uppercase tracking-[0.4em] text-[var(--bg-primary)]">
            Return to Archive
          </Text>
        </TouchableOpacity>
      </View>
    );
  }

  return <NoteEditor note={note} />;
});

export default function NotePage() {
  const { id } = useLocalSearchParams<{ id: string }>();
  if (!id) return null;
  return <EnhancedNoteEditor id={id} />;
}
