import { NextResponse } from "next/server";

/**
 * Tauri Update Server Endpoint
 * Documentation: https://v2.tauri.app/plugin/updater/
 * 
 * Target Example: linux-x86_64, windows-x86_64, darwin-aarch64
 * Version Example: 1.0.0
 */
export async function GET(
  req: Request,
  { params }: { params: Promise<{ target: string; version: string }> }
) {
  const { version } = await params;

  // 1. Fetch latest version from your GitHub Public Release Repo or a config file
  // For now, let's hardcode the latest. You should update this during release.
  const LATEST_VERSION = "1.0.0";
  const PUBLIC_RELEASE_URL = "https://github.com/YOUR_USERNAME/planner-releases/releases/download";

  // 2. Check if the requesting app needs an update
  if (version === LATEST_VERSION) {
    // 204 No Content means no update available
    return new Response(null, { status: 204 });
  }

  // 3. Return the update signature and download URL
  // Signature is generated by `tauri signer sign` command during build
  const updateData = {
    version: LATEST_VERSION,
    notes: "New features and bug fixes for the Daily Checklist.",
    pub_date: new Date().toISOString(),
    platforms: {
      "linux-x86_64": {
        signature: "SIGNATURE_FROM_BUILD_PROCESS",
        url: `${PUBLIC_RELEASE_URL}/v${LATEST_VERSION}/planner_${LATEST_VERSION}_amd64.AppImage.tar.gz`
      },
      "windows-x86_64": {
        signature: "SIGNATURE_FROM_BUILD_PROCESS",
        url: `${PUBLIC_RELEASE_URL}/v${LATEST_VERSION}/planner_${LATEST_VERSION}_x64_en-US.msi.zip`
      },
      "darwin-aarch64": {
        signature: "SIGNATURE_FROM_BUILD_PROCESS",
        url: `${PUBLIC_RELEASE_URL}/v${LATEST_VERSION}/planner_${LATEST_VERSION}_aarch64.app.tar.gz`
      }
    }
  };

  return NextResponse.json(updateData);
}
